# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  WPE_ENV_NAME:
    description: 'Your WPEngine site name(id)'
    required: true
  WPE_SSH_KEY_PUBLIC:
    description: 'Your SSH public key for WPE in Github Secret'
    required: true
  WPE_SSH_KEY_PRIVATE:
    description: 'Your SSH private key for WPE in Github Secret'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.WPE_ENV_NAME }}
    # - ${{ inputs.wpeSshKeyPublic }}
    # - ${{ inputs.WPE_SSH_KEY_PRIVATE }}