name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  WPE_ENV_NAME:
    description: 'Your WPEngine site name(id)'
    required: true
  WPE_SSH_KEY_PRIVATE:
    description: 'Your SSH private key for WPE in Github Secret'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.WPE_ENV_NAME }}
    - ${{ inputs.WPE_SSH_KEY_PRIVATE }}