name: 'WPEngine SSH Deploy'
description: 'Action to deploy to WPEngine via SSH'
inputs:
  WPE_ENV_NAME:
    description: 'Your WPEngine site name(id)'
    required: true
  WPE_SSH_KEY_PRIVATE:
    description: 'Your SSH private key for WPE in Github Secret'
    required: true
  DEST_PATH:
    description: 'Optional relative destination path'
    required: false
  SRC_PATH:
    description: 'Optional relative source path'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.WPE_ENV_NAME }}
    - ${{ inputs.WPE_SSH_KEY_PRIVATE }}