on: [push]

jobs:
  deployment_job:
    runs-on: ubuntu-latest
    name: Deploy to WPEngine
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: SSH Deploy to WPEngine
        uses: ./ # Uses an action in the root directory
        id: deploy
        with:
          WPE_ENV_NAME: "ttidev"
          WPE_SSH_KEY_PRIVATE: ${{ secrets.WPE_GIT_KEY_PRIVATE }}
          TPO_PATH: "rsync-test"
